"""Model adapter package"""

from ironflow_exp.models.base import (
    BaseModelAdapter,
    ClassificationModelAdapter,
    DetectionModelAdapter,
    EmbeddingModelAdapter,
    PredictionRecord,
    SegmentationModelAdapter,
    TrackingModelAdapter,
)
from ironflow_exp.models.default_specs import (
    create_default_model_registry,
    default_classification_specs,
    default_detection_specs,
    default_embedding_specs,
    default_model_specs,
    default_segmentation_specs,
)
from ironflow_exp.models.classification import (
    SUPPORTED_TIMM_CLASSIFIER_MODEL_IDS,
    SUPPORTED_TORCHVISION_CLASSIFIER_MODEL_IDS,
    SUPPORTED_ULTRALYTICS_YOLO_CLASSIFIER_MODEL_IDS,
    TIMM_CLASSIFIER_SPECS,
    TORCHVISION_CLASSIFIER_SPECS,
    ULTRALYTICS_YOLO_CLASSIFIER_FAMILIES,
    ULTRALYTICS_YOLO_CLASSIFIER_SCALES,
    MissingTimmDependencyError,
    MissingTorchvisionDependencyError,
    TimmClassificationAdapter,
    TimmClassifierReference,
    TorchvisionClassificationAdapter,
    UltralyticsYoloClassificationAdapter,
    UltralyticsYoloClassifierReference,
    UnsupportedTimmClassifierError,
    UnsupportedTorchvisionClassifierError,
    UnsupportedUltralyticsYoloClassifierError,
)
from ironflow_exp.models.detection import (
    SUPPORTED_ULTRALYTICS_YOLO_DETECTION_MODEL_IDS,
    ULTRALYTICS_YOLO_DETECTION_FAMILIES,
    ULTRALYTICS_YOLO_DETECTION_SCALES,
    MissingUltralyticsDependencyError,
    UltralyticsYoloDetectionAdapter,
    UltralyticsYoloModelReference,
    UnsupportedUltralyticsYoloModelError,
)
from ironflow_exp.models.tracking import (
    SUPPORTED_BYTETRACK_MODEL_IDS,
    ByteTrackModelAdapter,
    UnsupportedByteTrackModelError,
)
from ironflow_exp.models.placeholder_adapters import (
    PlannedClassificationAdapter,
    PlannedDetectionAdapter,
    PlannedEmbeddingAdapter,
    PlannedSegmentationAdapter,
    PlannedTrackingAdapter,
)
from ironflow_exp.models.compatibility_matrix import (
    ModelCompatibilityRow,
    build_model_compatibility_matrix,
    readiness_counts,
)
from ironflow_exp.models.registry import (
    AdapterMismatchError,
    DuplicateModelSpecError,
    ModelRegistry,
    ModelRegistryError,
    UnknownModelSpecError,
)
from ironflow_exp.models.spec import ModelSpec


__all__ = [
    'BaseModelAdapter',
    'AdapterMismatchError',
    'build_model_compatibility_matrix',
    'ByteTrackModelAdapter',
    'ClassificationModelAdapter',
    'create_default_model_registry',
    'default_classification_specs',
    'default_detection_specs',
    'default_embedding_specs',
    'default_model_specs',
    'default_segmentation_specs',
    'DetectionModelAdapter',
    'DuplicateModelSpecError',
    'EmbeddingModelAdapter',
    'ModelCompatibilityRow',
    'ModelRegistry',
    'ModelRegistryError',
    'ModelSpec',
    'MissingTimmDependencyError',
    'MissingTorchvisionDependencyError',
    'MissingUltralyticsDependencyError',
    'PlannedClassificationAdapter',
    'PlannedDetectionAdapter',
    'PlannedEmbeddingAdapter',
    'PlannedSegmentationAdapter',
    'PlannedTrackingAdapter',
    'PredictionRecord',
    'readiness_counts',
    'SegmentationModelAdapter',
    'SUPPORTED_BYTETRACK_MODEL_IDS',
    'SUPPORTED_TIMM_CLASSIFIER_MODEL_IDS',
    'SUPPORTED_TORCHVISION_CLASSIFIER_MODEL_IDS',
    'SUPPORTED_ULTRALYTICS_YOLO_CLASSIFIER_MODEL_IDS',
    'SUPPORTED_ULTRALYTICS_YOLO_DETECTION_MODEL_IDS',
    'TIMM_CLASSIFIER_SPECS',
    'TimmClassificationAdapter',
    'TimmClassifierReference',
    'TorchvisionClassificationAdapter',
    'TORCHVISION_CLASSIFIER_SPECS',
    'TrackingModelAdapter',
    'ULTRALYTICS_YOLO_CLASSIFIER_FAMILIES',
    'ULTRALYTICS_YOLO_CLASSIFIER_SCALES',
    'ULTRALYTICS_YOLO_DETECTION_FAMILIES',
    'ULTRALYTICS_YOLO_DETECTION_SCALES',
    'UltralyticsYoloClassificationAdapter',
    'UltralyticsYoloClassifierReference',
    'UltralyticsYoloDetectionAdapter',
    'UltralyticsYoloModelReference',
    'UnknownModelSpecError',
    'UnsupportedByteTrackModelError',
    'UnsupportedTimmClassifierError',
    'UnsupportedTorchvisionClassifierError',
    'UnsupportedUltralyticsYoloClassifierError',
    'UnsupportedUltralyticsYoloModelError',
]
