"""Adapter-facing task execution contracts for engine task records."""

from ironflow_exp.engine.tasks.artifact_writer import TaskArtifactWriter
from ironflow_exp.engine.tasks.augmentation_adapters import (
    AlbumentationsClassificationCropTaskAdapter,
    AlbumentationsDetectionBBoxTaskAdapter,
    AlbumentationsSegmentationMaskTaskAdapter,
    AugmentationPolicySmokeTaskAdapter,
    ClassificationCropAugmentationSmokeTaskAdapter,
    DetectionBBoxAugmentationSmokeTaskAdapter,
)
from ironflow_exp.engine.tasks.base import (
    BaseTaskAdapter,
    TaskDependencyContext,
    TaskAdapterResult,
    TaskExecutionContext,
    TaskExecutionPlanResult,
    TaskExecutionResult,
)
from ironflow_exp.engine.tasks.executor import AdapterTaskExecutor
from ironflow_exp.engine.tasks.model_task_adapters import (
    ClipEmbeddingTaskAdapter,
    DFineDetectionTaskAdapter,
    Dinov2EmbeddingTaskAdapter,
    Dinov3EmbeddingTaskAdapter,
    GroundingDinoOpenVocabDetectionTaskAdapter,
    MMDetectionTaskAdapter,
    PlannedDetectionTaskAdapter,
    PlannedEmbeddingTaskAdapter,
    PlannedSegmentationTaskAdapter,
    REAL_MODEL_TASK_ADAPTER_KEYS,
    RealModelTaskAdapter,
    RfDetrDetectionTaskAdapter,
    RtDetrDetectionTaskAdapter,
    RtDetrV2DetectionTaskAdapter,
    LwDetrDetectionTaskAdapter,
    SamPromptableSegmentationTaskAdapter,
    SiglipEmbeddingTaskAdapter,
    TimmClassifierTaskAdapter,
    TorchvisionClassifierTaskAdapter,
    UltralyticsYoloClassifierTaskAdapter,
    UltralyticsYoloSegmentationTaskAdapter,
    UltralyticsYoloTaskAdapter,
    YoloWorldOpenVocabDetectionTaskAdapter,
)
from ironflow_exp.engine.tasks.registry import (
    DuplicateTaskAdapterError,
    TaskAdapterRegistry,
    TaskAdapterRegistryError,
    UnknownTaskAdapterError,
)
from ironflow_exp.engine.tasks.transform_adapters import (
    BotSortTrackingTaskAdapter,
    ByteTrackTaskAdapter,
    DetectionToClassificationCropTaskAdapter,
    ManifestClassificationSmokeTaskAdapter,
    ManifestDetectionSmokeTaskAdapter,
    ManifestSegmentationSmokeTaskAdapter,
    OCSortTrackingTaskAdapter,
    build_builtin_task_adapter_registry,
)


__all__ = [
    'AdapterTaskExecutor',
    'AlbumentationsClassificationCropTaskAdapter',
    'AlbumentationsDetectionBBoxTaskAdapter',
    'AlbumentationsSegmentationMaskTaskAdapter',
    'AugmentationPolicySmokeTaskAdapter',
    'ClassificationCropAugmentationSmokeTaskAdapter',
    'DetectionBBoxAugmentationSmokeTaskAdapter',
    'BaseTaskAdapter',
    'BotSortTrackingTaskAdapter',
    'ByteTrackTaskAdapter',
    'DuplicateTaskAdapterError',
    'ClipEmbeddingTaskAdapter',
    'DFineDetectionTaskAdapter',
    'DetectionToClassificationCropTaskAdapter',
    'Dinov2EmbeddingTaskAdapter',
    'Dinov3EmbeddingTaskAdapter',
    'GroundingDinoOpenVocabDetectionTaskAdapter',
    'ManifestClassificationSmokeTaskAdapter',
    'ManifestDetectionSmokeTaskAdapter',
    'ManifestSegmentationSmokeTaskAdapter',
    'MMDetectionTaskAdapter',
    'OCSortTrackingTaskAdapter',
    'PlannedDetectionTaskAdapter',
    'PlannedEmbeddingTaskAdapter',
    'PlannedSegmentationTaskAdapter',
    'REAL_MODEL_TASK_ADAPTER_KEYS',
    'RealModelTaskAdapter',
    'RfDetrDetectionTaskAdapter',
    'RtDetrDetectionTaskAdapter',
    'RtDetrV2DetectionTaskAdapter',
    'LwDetrDetectionTaskAdapter',
    'SamPromptableSegmentationTaskAdapter',
    'SiglipEmbeddingTaskAdapter',
    'TaskAdapterRegistry',
    'TaskAdapterRegistryError',
    'TaskAdapterResult',
    'TaskArtifactWriter',
    'TaskDependencyContext',
    'TaskExecutionContext',
    'TaskExecutionPlanResult',
    'TaskExecutionResult',
    'TimmClassifierTaskAdapter',
    'TorchvisionClassifierTaskAdapter',
    'UltralyticsYoloClassifierTaskAdapter',
    'UltralyticsYoloSegmentationTaskAdapter',
    'UltralyticsYoloTaskAdapter',
    'UnknownTaskAdapterError',
    'YoloWorldOpenVocabDetectionTaskAdapter',
    'build_builtin_task_adapter_registry',
]
